[INFO][190826 15:33:31,739][org.hibernate.validator.internal.util.Version.<clinit>(Version.java:27)][HV000001: Hibernate Validator 4.3.2.Final]
[INFO][190826 15:33:31,900][org.springframework.context.support.AbstractApplicationContext.prepareRefresh(AbstractApplicationContext.java:583)][Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@1134affc: startup date [Mon Aug 26 15:33:31 CST 2019]; root of context hierarchy]
[INFO][190826 15:33:32,102][org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:317)][Loading XML bean definitions from class path resource [application-bean.xml]]
[WARN][190826 15:33:33,082][org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)][Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'user' defined in file [D:\git\leb\target\classes\spring\aop\validate\User.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanInitializationException: Bean state is invalid: phone - 手机号不能为空！]
